// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function callMS() {
	// BEGIN USER CODE
const xhr = new XMLHttpRequest();

          xhr.open('GET', 'https://jsonplaceholder.typicode.com/todos/1');
          xhr.send();

          xhr.addEventListener('readystatechange', () => {
            if (xhr.readyState === 4) {
              console.log(xhr.status);
              console.log(xhr.response);
            }
          });

          xhr.ontimeout = () => {
            console.log('timeout');
          };
	// END USER CODE
}
